function conv = tanh_k_by_k_op()
    tol = 1.0e-6; % Default (1.0e-6)
    fun = @(r) 1./(8*pi^3*r.*(1+r)) .* e.^(-r.^2/4);
    cut_off = 20;
    res = 0.1;
    r_vec = [0 : res : 25];
    ref_fun = @(k) (!k) + (!!k).*tanh(k)./k/(2*pi)^2;
    F = (2*pi) * hankel_transform(0, fun, cut_off, r_vec, tol);
    F_ref = ref_fun(r_vec);

    % Compare functions
    title = "Comparison";
    ph = plot(r_vec, F_ref, r_vec, F); % Returns a graphics handle to the plot
    fh = gcf(); % Returns a graphics handle to the figure
    ah = gca(); % Returns a graphics handle to the axes
    set(ah, "title", title)
    %print(strcat("C:/Work/master_thesis/matlab_code/2D_wave_equation/", lower(title), ".tex"     ), "-dtex" );
    %print(strcat("C:/Work/master_thesis/matlab_code/2D_wave_equation/", lower(title), "_tikz.tex"), "-dtikz");
    print(strcat(lower(title), ".tex"     ), "-dtex" );
    %delete(strcat(lower(title), "-inc.eps"));
    print(strcat(lower(title), "_tikz.tex"), "-dtikz");
    
    % Ratio
    title = "Ratio";
    ph = plot(r_vec, F ./ F_ref);
    fh = gcf(); % Returns a graphics handle to the figure
    ah = gca(); % Returns a graphics handle to the axes
    set(ah, "title", title)
    %print(strcat("C:/Work/master_thesis/matlab_code/2D_wave_equation/", lower(title), ".tex"     ), "-dtex" );
    %print(strcat("C:/Work/master_thesis/matlab_code/2D_wave_equation/", lower(title), "_tikz.tex"), "-dtikz");
    print(strcat(lower(title), ".tex"     ), "-dtex" );
    %delete(strcat(lower(title), "-inc.eps"));
    print(strcat(lower(title), "_tikz.tex"), "-dtikz");
    
    delete("*-inc.eps"); % Delete files generated by matlab
endfunction